### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by philschatz** [openstax/cnx#1]
@reedstrm notes to self (from presenting to BARB folks):

- add red back-arrow into legacy so that publishes that came in via press are visible on legacy
- (in pink) archive and baker will need to pull data from the new press DB rather than the legacy DB
- (in pink) add labels to the DBs (content, resources, exercises)
- (in purple) bakedPDF will need to get information from archive

Naming (sticky note names):

- Green: Bake Store
- Red: Legacy2Press
- Purple: BakedPDF
- Brown: Events
- Pink: Press Store
- Orange: Fresh Content APIs
- End Goal/Unicorn Treats

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
