### ISSUE TITLE
Search page layout not so responsive

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#125]
## Overview
1. go to https://cnx.org/browse on a mobile device (e.g., iPhone)
2. notice that some of the headings and images look squished.
This looks particularly bad on the line with "Science and Technology".

![](https://trello-attachments.s3.amazonaws.com/581c83e5cae45416fa9bf5e2/5a8c71f033276ef74e92de25/c853f334da5ad60a21d4418ba4da1a21/image.png)

## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by ambersdai** [comment]
From Kerwin: Actually I'd love to see webview get a whole new design for Unicorn (which would include responsive of course), to align it with the user experience for OSWeb etc., and so that webview would actually get some love (especially if it's owned by frontend developers currently with the textbook team). But that's another discussion.

As far as this particular bug goes, it's really more of a "hey, I filed it" sort of thing (actually this was found by our offshore tester). I personally don't consider it a priority.

**Comment by edwoodward** [comment]
This has been fixed

![screenshot from 2019-02-01 12-16-50](https://user-images.githubusercontent.com/1394695/52141424-52678800-261b-11e9-994c-799824d17bbb.png)
