### ISSUE TITLE
remove Google Plus sharing link from books

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#128]
## Overview

1. Go to any book on cnx, e.g. https://cnx.org/contents/r-QzKsl_@7.23:_97x1rAv@2/Introduction-to-Sociology
2. Click the G+ icon in the upper right
3. You get taken to a 403 forbidden error page.
Severity: [ ] High [x ] Medium [ ] Low
Frequency of Occurence: [ x] High [ ] Medium [ ] Low
## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
We should remove the G+ icon from that page entirely. In the footer of the CNX site we have already removed the link to Google Plus that had been there.
## Next Steps for the User
If the card is accepted or rejected, what does user need to know now? They should forget Google Plus ever existed (like the rest of us).

**Comment by edwoodward** [comment]
This has been completed.
