### ISSUE TITLE
Remove option for module PDFs

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#131]
### Description
Many of the OS PDFs do not generate module PDFs and we are starting to have problems with the Latex PDF pipeline and have no one on staff to work on it. The PDF issues are consuming a large volume of Customer Service and developer time. We should remove this option so that users must create a collection to have the PDF download option.

### Impact
Severity: [ X] High [ ] Medium [ ] Low
Frequency of Occurrence: [ ] High [ ] Medium [ ] Low## PRs
What PRs need to be merged to complete this task/feature

## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by Bkblodget** [comment]
this work was addressed with https://github.com/openstax/cnx/issues/38 and https://github.com/openstax/webview/issues/2133
