### ISSUE TITLE
Header changes when scrolling down a book page

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#137]
### Steps
1. go to https://staging.cnx.org/contents/rydUIGBQ@10.1:Gofkr9Oy@9/Preface. Note what the grey nav header with the social media icons looks like.

2. Scroll down the page. Note that same header changes. The header and font shrink, and the social media icons disappear.

Link to animated gif of bug: https://user-images.githubusercontent.com/11298165/36496224-3c17135a-16fd-11e8-8dd6-51401318fcb4.gif

NOTE:
This is also live on production, except it's worse on staging now: https://cnx.org/contents/r-QzKsl_@7.23:_97x1rAv@2/Introduction-to-Sociology

### Environment
Only able to see this on OSX El Capitan, Chrome 64. Cannot reproduce on Firefox 58. Ross also could not reproduce in Chrome 64 on Linux. Alan could not reproduce on High Sierra.

![](https://trello-attachments.s3.amazonaws.com/581c83e5cae45416fa9bf5e2/5a8daea824ff1c2fe7ab248e/ab41b86745358c5823c9ac281939eac6/image.png)

## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by edwoodward** [comment]
I think this change was done to make the header smaller on mobile devices. Otherwise the header takes up half of the phone's screen. Closing.
