### ISSUE TITLE
Extract documentation from Trac

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#153]
## Overview
User bug reporting for Legacy CNX uses Trac and needs to be changed to use Salesforce.

Background

Trac (boning.cnx.rice.edu, aka trac.cnx.org) runs on very old hardware (IBM Bladecenter LS21 - probably 2009 or earlier) and runs a very old, no longer support Linux version (Debian 5 - end of life 2012, current version is 8, but we now use Ubuntu).

Continuing to use old hardware represents a reliability risk. Continuing to use old operating systems represents a security and reliability risk.
## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by ambersdai** [comment]
One potential path to recovering the data would be to stand up a recent trac instance, and upgrade the old system to that:

https://trac.edgewall.org/wiki/TracUpgrade

Current system is 0.11. Upgrading to current stable would be three steps: 0.11 -> 0.12, ->1.0 -> 1.2

Alternative would be to extract the wiki parts into another wiki (github repo wiki, perhaps?) -Ross

**Comment by edwoodward** [comment]
Trac has been decommissioned, so closing this.
