### ISSUE TITLE
Footer tabs content looks like doodoo in mobile view

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#171]
## Overview
Load any book page in a mobile browser (e.g., iPhone -- or a very narrow browser window) and scroll all the way down to the footer with "Downloads", "History", "Attribution" and "More Information" tabs.

1) Click "History", notice the content is cut off on the right side (and you can't scroll horizontally to see it).

2) Click on "Downloads" available at the bottom>> Scroll up>> Observe "Book"/"Page" Button -- it floats weirdly.

## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

![](https://trello-attachments.s3.amazonaws.com/581c83e5cae45416fa9bf5e2/5aa16c50fb9ada027bba6323/1247438e275dd84608c487f99fce2227/book-tab-out-of-place.png)

![](https://trello-attachments.s3.amazonaws.com/581c83e5cae45416fa9bf5e2/5aa16c50fb9ada027bba6323/b2ebdc41618e237f81ec067589f07465/footer-truncated.png)

**Comment by edwoodward** [comment]
It has been improved, so I am closing this.
