### ISSUE TITLE
CNX Mobile - Content in End-of-Page Items Unscrollable

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#172]
## Overview
In Mobile, the content at the end of the page (in items Downloads, History, Attribution, More Information) is shifted to the right of the screen and unscrollable. Content should be aligned to the left side of the screen and resized or scrollable.

### Steps to Reproduce
- Product: [ ] Tutor [ ] Concept Coach [ ] OS Web [ ] Content Production Toolkit [x] CNX
- How many times were you able to reproduce the issue? Multiple
- Images or Screenshots Included: [x] Yes [ ] No (attach below)
### Environment:
- Instance: [x] production [ ] qa [ ] staging [ ] dev [ ] content
- OS: [ ] Mac OSX [ ] Windows [x] iOS [ ] Android
- Browser: [ ] Chrome [ ] Firefox [x] Safari [ ] Opera [ ] IE [ ] Edge
### Impact
- Severity: [ ] High [x] Medium [ ] Low
- Frequency of Occurrence: [x] High [ ] Medium [ ] Low
## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

<img width="451" alt="screen shot 2018-10-29 at 2 53 50 pm" src="https://user-images.githubusercontent.com/27330377/47676368-7930a100-db8a-11e8-9a8e-67ba1eac9c27.png">

**Comment by edwoodward** [comment]
This has been fixed. Closing.

![screenshot from 2019-02-01 12-58-53](https://user-images.githubusercontent.com/1394695/52143465-28b15f80-2621-11e9-8c25-cba1430b61b0.png)
