### ISSUE TITLE
Numbering

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#184]
## Overview
As a user of the EPUB, I want numbering to match Webview and the PDF, so I can assign across the formats (instructor) and use them interchangeably (all users).

Epic Doc: https://docs.google.com/document/d/1y1r74ZbovQmHxywJjxcplTWJiqxzY60-2BJA8fgdjaI/edit#
## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Numbering of figures, examples, exercises, chapters, sections, (...?) matches across PDF, Webview, and EPUB.

**Comment by edwoodward** [comment]
Added to #183. Closing.
