### ISSUE TITLE
Baked PDF - Common and Book-Specific Recipe Spike

### ISSUE THREAD

**Issue by edwoodward** [openstax/cnx#189]
### Description

This spike is to determine if we can have common baking followed by book-specific baking. The common baking would be the same for all books (clean up HTML and create a single book HTML file). The book-specific baking would handle numbering and collation. The goal of this spike is to help us know that this approach will work and the time need to execute both steps.

Links:

- _Some_ Common stuff (some may be overridden): https://github.com/Connexions/cnx-recipes/blob/master/recipes/books/_common-stuff.scss
- The recipes (see `books/`) https://github.com/Connexions/cnx-recipes/tree/master/recipes

----------------
**Steps to Reproduce the bug or Details about Change:** _What, Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by openstaxalina** [comment]
Adding release labels for tracking purposes only.

**Comment by Bkblodget** [comment]
moving this over to https://github.com/openstax/cnx/issues/229
