### ISSUE TITLE
UNIFIED: CloudFront header forwarding and caching

### ISSUE THREAD

**Issue by BruceP99166** [openstax/cnx#199]
### Description
Enumerate the client headers that the backend servers use and which of those change the response from backend servers, so that CloudFront will cache out content effectively.

For Unified Reading Experience

### Problem Description
In order for CloudFront to cache content for us, we have to enumerate which headers we want it to forward to our origins.  For CNX archive (resources and specials URLs), list which headers need to be forwarded to the backend servers by CloudFront and of those say which change the provided response.

### Notes
- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/header-caching.html
- Timing: No Later Than Jan 2019
- Blocks: Nothing

### Acceptance Criteria
- Unified team gets a list of headers marked with which impact response content

**Comment by brittweinstein** [comment]
@Bkblodget we decided to close this in sprint planning, right?
