### ISSUE TITLE
URL shortcut to see CNXML doesn't work on production

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx#20]
Previously I have been able to use legacy.cnx.org/content/m#####/version/source to see the cnxml without checking out the module, but instead it currently displays only the text of the module with no formatting, even if I'm logged in as a global manager.

**Comment by edwoodward** [comment]
This is working on production - https://legacy.cnx.org/content/m10656/latest/source

![screenshot from 2019-01-31 13-48-11](https://user-images.githubusercontent.com/1394695/52081060-e32c5e00-255e-11e9-9352-8de63cc280a3.png)

Closing issue

**Comment by oscryan** [comment]
Try this one: https://legacy.cnx.org/content/m68108/latest/source
<img width="949" alt="screen shot 2019-01-31 at 1 49 49 pm" src="https://user-images.githubusercontent.com/1895432/52081125-1838b080-255f-11e9-95b9-7320b93f0e6a.png">

**Comment by Bkblodget** [comment]
The link works for me: 

![screen shot 2019-01-31 at 1 56 10 pm](https://user-images.githubusercontent.com/11299035/52081515-06a3d880-2560-11e9-98e4-17d37200b0de.png)

**Comment by oscryan** [comment]
ok this is clearly my problem then. I'll try and figure out what it is.
