### ISSUE TITLE
Request: Reviving Mayu's url conversion tool

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx#201]
Hello. This is a blast from the past. Just wanting to see if this can be revived and for it to stay alive so we can make book maps easier...

Currently we are looking to migrate something from the TEA server. I don't think this tool works there. Nor has it worked in a long time.

https://github.com/Rhaptos/cnx-tools/tree/master/cnx-url-conversion-tool

Thank you.

xoxo, Larissa

**Comment by openstaxalina** [comment]
Propose reviewing the tool in the coming sprint.  Determine what fixes/improvements are needed, and schedule for Q1.

**Comment by openstaxalina** [comment]
@edwoodward will be able to work on this once we know what the issues are.

**Comment by edwoodward** [comment]
PR: https://github.com/Connexions/cnx-tools/pull/3

**Comment by BryanEliDimas** [comment]
@Bkblodget @edwoodward Approved the PR.

**Comment by Bkblodget** [comment]
@Bkblodget to contact a CM to test this

**Comment by brittweinstein** [comment]
@marcjeannott will test on the CM side - removing release label until this is done.

**Comment by marcjeannott** [comment]
Larissa is right there’s no way to select which server you’re talking about, and when I used a collection number I got off of tea server, it gave me an error. 

Traceback (most recent call last):
  File "conversion-tool.py", line 415, in <module>
    main()
  File "conversion-tool.py", line 403, in main
    convertedList, errorIdList, count = convertColId(idList[0], printModules)
  File "conversion-tool.py", line 250, in convertColId
    findModuleIds(section, moduleIdList)
  File "conversion-tool.py", line 272, in findModuleIds
    findModuleIds(subSection, moduleIdList)
  File "conversion-tool.py", line 271, in findModuleIds
    for subSection in section['contents']:
KeyError: 'contents'

**Comment by Bkblodget** [comment]
@marcjeannott Can you clarify a bit more on your last point/request about the book UUID? Maybe provide a screenshot? I _think_ you are asking for the exported file to say **Book's UUID** instead of **books UUID**. Is that correct?

**Comment by marcjeannott** [comment]
Right, from a CM perspective we know that first UUID is the book's because it begins with col, but third parties wont. Oops, yes Book's UUID. I've updated the last part to include a screenshot as well as an example case I had with Alina.

**Comment by openstaxalina** [comment]
I will add that when you just see the list of UUIDs by themselves, they are all just strings of letters and numbers, so there is really no way to know that the very first one is for the book.  I assumed it was for the first module!

**Comment by brittweinstein** [comment]
A card exists for future work to get this on TEA server in Q2. I will close this card for now.
