### ISSUE TITLE
Redoing Testing

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx#212]
### Description

**Change or Bug** _Choose the title for the issue or pick the correct lable._

----------------
**Steps to Reproduce the bug or Details about Change:** _What, Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by omehes** [comment]
No Offshore Regression tests (2018.12.19) - OK (no new issues)


staging.cnx.org

{"date": "2018-12-19 10:45:18 CST",
 "webview": "9afc493b8f9c2fee608555a680fccda15d57d569 (v0.43.0)",
 "cnx-archive": "4.7.0",
 "cnx-publishing": "0.14.1",
 "oer.exports": "xiao.xiao v0.68.0",
 "press": "7.0.1",
 "cnx-deploy": "v2.33.3"
}
