### ISSUE TITLE
 SEO: Remove “Disallow:  /content$” from robots.txt

### ISSUE THREAD

**Issue by Bkblodget** [openstax/cnx#215]
## Overview

Remove “Disallow:  /content$” from robots.txt - allow spiders to go to /content$ folders. 

When content folders are disallowed from robots.txt, Google may still display the old link in search results, but it will be broken; search results will say “there is no information for this link” and will redirect to another page if a user clicks. Removing this restriction from robots.txt will allow Google to access the page but see that canonical tags are pointing to different content, and will tend to prefer that other content.

## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by Bkblodget** [comment]
verify by going to cnx.org/robots.txt and confirming content$ does not have disallow.

**Comment by omehes** [comment]
verified in released version on cnx.org - /content$ is missing - OK

{"date": "2019-01-22 10:23:30 CST",
 "webview": "65e33ad4775417bd5dfcb698d5cab69f1d594466 (v0.44.0)",
 "cnx-archive": "4.8.0",
 "cnx-publishing": "0.15.0",
 "oer.exports": "ymmy.yeti v0.69.0",
 "press": "8.0.1",
 "cnx-deploy": "v2.34.2"
}
