### ISSUE TITLE
UNIFIED: CloudFront cookie forwarding

### ISSUE THREAD

**Issue by kjdav** [openstax/cnx#217]
##Overview
Enumerate the cookies that CloudFront should forward to archive for it to serve resources and specials, and say which cookies impact the content that is returned, so that CloudFront can cache content effectively and correctly.

CloudFront can be configured to cache based on cookies forwarded from clients to the origin.  When we know what archive needs for resources and specials and how those cookies impact what is returned by archive, we can configure CloudFront to behave correctly.

Notes
JP guesses that archive doesn’t need any cookies and doesn’t change responses based on cookies, so this might be an easy card.
CloudFront: Caching Content Based on Cookies
Timing: No later than Feb 12Jan 2019
Blocks:
Nothing

Acceptance Criteria
Unified teamJP gets a list of cookies marked with which impact response content
## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?

**Comment by edwoodward** [comment]
Archive does not use cookies, so there is nothing to do on this card.

**Comment by Bkblodget** [comment]
@jpslav @kjdav Is it okay if I close this card given Ed's comment above?

**Comment by karenc** [comment]
I agree with @edwoodward, archive doesn't use cookies.

**Comment by jpslav** [comment]
Yes, close.
