### ISSUE TITLE
Remove “Disallow:  /content$” from robots.txt - allow spiders to go to /content$ folders

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx#22]
##Overview
When content folders are disallowed from robots.txt, Google may still display the old link in search results, but it will be broken; search results will say “there is no information for this link” and will redirect to another page if a user clicks. Removing this restriction from robots.txt will allow Google to access the page but see that canonical tags are pointing to different content, and will tend to prefer that other content.

## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by reedstrm** [comment]
duplicated by #215
