### ISSUE TITLE
Fix the content copy tool

### ISSUE THREAD

**Issue by Bkblodget** [openstax/cnx#223]
## Overview
The content copy tool which is used by Content Managers to migrate content from one server to another is broken. Because the Books team needs the content copy tool to migrate content for books being released in Q1, this is a high priority issue. **The next migration is on 2/22/19**. Below is a list of scenarios CMs have encountered when running the content copy tool. 

For each scenario, the supporting documents are attached (mapping spreadsheet, json settings file & error log) here: [ContentCopyToolErrorDocuments.zip](https://github.com/openstax/cnx/files/2793127/ContentCopyToolErrorDocuments.zip)

This is the user documentation for the tool:  [Content Copy Tool User Manual](https://docs.google.com/document/d/1FbIy8pSRoJPjDXsOBVTAzV3BjM2ZSj9SYypPY_TYXio/edit#heading=h.i2j4pmol69zz) 

## Scenarios 
1. Marc (using v.1.2) - migrating content from https://content02.cnx.org/ to https://devb.cnx.org/
- Failed workgroup creation 
- Failed content copying 
- False reporting: tool reported that some modules were successfully copied, but no content appeared in the module on legacy. Other instances of this are when the tool reports that modules were successfully created, copied or published when they actually were not. 

2. Larissa (using v.1.2) - migrating content from https://content02.cnx.org/ to https://staging.cnx.org/
- Successfully created workgroups, modules
- Successfully copied content
- Successfully changed roles
- Successfully created a collection
- Successfully published modules and collection
- This is the only recent instance we have of successfully being able to complete the content copy process. 

3. Larissa (using v.1.2) - creating a collection on https://devb.cnx.org/
- Collection creation failed with many errors

4. Ryan (using v.1.2) - migrating content from https://content03.cnx.org/ and https://content04.cnx.org/ to https://.cnx.org/
- Successful content copying
- False reporting: tool reported successful publishing of modules, however, all modules remained in a modified state. The roles for each module had not been accepted but the tool nor the log record this error - it just thinks the modules are published. 

5. Ryan (using v.1.2) - migrating content from https://tea.cnx.org to https://content04.cnx.org/
- Failed workgroup creation
- Failed module creation
- Failed content copying
- Failed publishing

6.  Ryan (using v.1.2) - same scenario as #3 but run from Ryan's computer
- Collection creation failed with many errors. 

## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Users will be able to successfully:
- create workgroups
- create modules
- copy content
- assign roles
- accept roles
- publish modules
- created collection
- publish collection
- these function should work to and from *all environments* (devb, tea, content02, content03, content04, staging, qa, and production)

**Comment by Bkblodget** [comment]
@edwoodward I assigned you this issue to review in preparation for bringing on someone to work exclusively on this task. Will the information I provided suffice?

**Comment by tomjw64** [comment]
Problems:
- When using `response = requests.post(...)`, if the target url redirects e.g. http -> https, then the post will be unsuccessful and `response.url` will simply give the url to which you were redirected. This causes seemingly correct config/settings json files to throw errors.

**Comment by edwoodward** [comment]
@Bkblodget It would be helpful to have the .tsv file and settings.json for each of the problems listed. This will help the developers recreate the error.

**Comment by Bkblodget** [comment]
@m1yag1 This is pretty much all the information we have been able to gather

**Comment by m1yag1** [comment]
I also suggest that the imports be made more explicit. Currently, in the `content_copy.py` file there is the use of `*` imports which makes it really hard to tell what is being imported from where. It is also a practice that is frowned upon. Example: https://github.com/openstax/cnx-tools/blob/master/content-copy-tool/content-copy.py#L6-L8

**Comment by brittweinstein** [comment]
@Bkblodget would it be possible to convert this issue to an epic and have the issues that Marvin is working on fall under that?

**Comment by tomjw64** [comment]
Safe servers for Marvin and I to work on as per Ed's instructions:
- dev.cnx.org
- devb.cnx.org
- autode01.cnx.org
