### ISSUE TITLE
Content Status page returns 503 error on staging.cnx.org

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx#240]
### Description

When trying to visit the [content status page](https://staging.cnx.org/a/content-status/) on staging a 503 error is being returned. This is causing automated functional tests for the content status page to fail.

----------------
**Steps to Reproduce the bug or Details about Change:** _What, Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

1. Open a browser
2. Go to url https://staging.cnx.org/a/content-status
3. See the 503 backend fetch error

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [x] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [x] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [x] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

None
----------------
**Images or Screenshots** (_attach below_)

![image](https://user-images.githubusercontent.com/8730430/53036382-3c403100-343d-11e9-87e8-867c322aca28.png)

**Comment by pumazi** [comment]
Ok, apparently this has the same issue as #236, but this can't be resolved with a simple PR on cnx-deploy. I'll fix the imports in cnx-publishing; then I'll release the package, etc.

**Comment by pumazi** [comment]
I've created a fix and I've released cnx-publishing `v0.15.1`. I'll link the cnx-deploy PR when pyup has created it.

**Comment by pumazi** [comment]
Deployed and resolved
