### ISSUE TITLE
Items stuck in the baking queue block further work.

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx#257]
# Scenario

While testing recipe fixes we manually inject the updated recipe into a collection set to the CCAP version of a collection to force it to bake with that specific recipe, and on occasion one of these bakes will get stuck in a "Queued" state, or won't report back that it has errored out, which causes the system to think that is still working on that one collection indefinitely. This prevents work from being done because it blocks other attempts to re-bake the original collection or any other collection on that environment.

# Reproducibility Details

**URL / Location**

Visible on but not intractable with on https://easyvm5.cnx.org/a/content-status/ (or the equivalent GOB page on each environment)

**Were you able to reproduce the issue?** 

[  ] Not able to reproduce
[ X ] Intermittent occurrence
[  ] Readily reproducible

*  **Steps to reproduce**:

1. Check out the collection, set it to use `CCAP <Recipe>` on the Parameters tab, and republish with appropriate comment.
2. Open the non-legacy view of the collection on the environment you'll be working on, open the "More Info" tab at the bottom and copy the ID.
3. SSH into the server, and `wget` the raw of the assignable webview recipe for the collection.
4. Run `/var/cnx/venvs/archive/bin/cnx-archive-inject_resource /etc/cnx/archive/app.ini --media-type text/css --resource-filename ruleset.css <collID> <ruleset.css>`
5. Once the book is rebaked, run `sudo varnishadm -T 127.0.0.1:6082 -S /etc/varnish/secret ban req.url '~' '.'` to clear the server cache, reload the page w/o cache using the Network tab of browser's dev tools and view the changes.

* **Images or screenshots Included:** 

[ X ] Yes (attached below)
[  ] No

![2019-03-07_10-42-02.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/39d183c7-b14e-4bfd-b89d-5c7644782e58)
_Screenshot taken with a refreshed GOB page on 2019-03-07T16:50Z_

# Environment:

**Instance**

[ X ] dev
[ X ] staging
[ ? ] production

**Comment by Stackblocks** [comment]
Dennis found that the file system on easyvm5.cnx.org had filled up. It is possible that this "sticking" also involves a component of cranking out a bunch of junk that fills up the server, locking it up.

**Comment by pumazi** [comment]
If only there were a means to do initial debug steps on these environments. Back to basics, for example: https://edu.gcfglobal.org/en/computerbasics/basic-troubleshooting-techniques/1/

My initial common troubleshooting/debug steps might look something like:
1. is it plugged in
2. are the status lights showing good health
3. (dive deeper into the expected behavior)

I don't know about you, but being able to see a dashboard to determine what's wrong with a situation seems like a good starting point.

**Comment by Stackblocks** [comment]
Absolutely agreed. 

Additionally, it's worth noting on the record in this issue that Dennis pointed out that this is a similar issue to the one that led us to decommission devb, and easyvm5 has more space than devb did so this is definitely a behavior shared across multiple environments of differing type.

**Comment by Stackblocks** [comment]
Was unable to change branches on the server today because it was full to the gills again. Dennis deleted the Data.fs.pack file to clear up space. Thomas investigated and found that a lot of sizeable epubs were piling up and may be contributing to the congestion.
