### ISSUE TITLE
Baked PDF CLI - Assemble module HTML files into a single HTML file

### ISSUE THREAD

**Issue by BryanEliDimas** [openstax/cnx#272]
# Description

Given module HTML files, assemble them into a single HTML file.

# PRs
https://github.com/openstax/nebuchadnezzar/pull/122
https://github.com/openstax/nebuchadnezzar/pull/132
https://github.com/openstax/nebuchadnezzar/pull/133

# Related Issues
https://github.com/openstax/nebuchadnezzar/issues/128 
https://github.com/openstax/nebuchadnezzar/issues/127

# Test Plan

# Acceptance Criteria

# Technical Notes
- Use the models located in [cnxepub/models.py](https://github.com/Connexions/cnx-
epub/blob/51096c21f1f492be7285c3493c14147a5c17d074/cnxepub/models.py)

- The collection HTML script is in [scripts/single_html/main.py](https://github.com/Connexions/cnx-epub/blob/51096c21f1f492be7285c3493c14147a5c17d074/cnxepub/scripts/single_html/main.py). 
It takes an EPUB as input and outputs a collection HTML file.

- For detailed technical background, see the [Baked PDF Technical Brief](https://docs.google.com/document/d/12OOzczQx-AJKN3C2pDgbs9I1rQ8XmUchcET5k0rCGH4/edit#heading=h.rdrp96p2bs5x) GDoc.

**Note: moved this issue from https://github.com/openstax/baked-pdf/issues/41 and that's why comments have extra info like when the comment was added.**

**Comment by brittweinstein** [comment]
@pumazi @karenc please link remaining related issues to this epic.

**Comment by pumazi** [comment]
Sorry, I think some duplication happened in this regard and I attached most of the work to that item rather than this one. @brittweinstein, I'll close this in favor of #254. Reopen if you feel it still needs to be around.
