### ISSUE TITLE
 LEGACY PORTION: Change Request: Remove option for module PDFs

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx#38]
# Description

Many of the OS PDFs do not generate module PDFs and we are starting to have problems with the Latex PDF pipeline and have no one on staff to work on it. The PDF issues are consuming a large volume of Customer Service and developer time. We should remove this option so that users must create a collection to have the PDF download option.

#Impact
* **Severity**: [ X] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

#Acceptance
-module PDF option does not appear in any of the following pages
(1) "new" webview in the "Downloads" tab **when toggled to page or viewing only a page.  The Book PDF option MUST remain intact.**
(2) Legacy: module view, "Download module as..."
(3) Legacy: module view, "Downloads" header (ex. https://legacy.cnx.org/content/m60207/1.13/content_info#cnx_downloads_header)
(4) Legacy: collection view, "Download" --> "Download Module As:"

**Comment by openstaxalina** [comment]
Document all the places this option appears.

**Comment by openstaxalina** [comment]
Need cards in cnx-archive, Rhaptos...(multiple)

**Comment by reedstrm** [comment]
This will need work in cnx-deploy to remove the logic in legacy-varnish vcl that does the module PDF download and retry to generate.

**Comment by openstaxalina** [comment]
screenshots of the areas that need updating:
(1)
![NewCNXModulePDFScreenshot.png](https://images.zenhubusercontent.com/5b57372fb01a900cfd923015/3162dc48-72ed-4226-80af-995d08daaa38)

**Comment by openstaxalina** [comment]
(2)
![Legacy2ndCase.png](https://images.zenhubusercontent.com/5b57372fb01a900cfd923015/684e9cca-af2e-4672-93d2-a8aacac9fb15)

**Comment by openstaxalina** [comment]
(3) https://legacy.cnx.org/content/m60207/1.13/content_info#cnx_downloads_header
![Legacy3rdOption.png](https://images.zenhubusercontent.com/5b57372fb01a900cfd923015/ce202b47-7edf-4d4b-828f-689c5e50ceff)

**Comment by openstaxalina** [comment]
(4) https://legacy.cnx.org/content/m63924/latest/?collection=col12160/latest
![Legacy4thCase.png](https://images.zenhubusercontent.com/5b57372fb01a900cfd923015/13b27df3-f949-4e34-8d7c-ad7827910fb5)

**Comment by edwoodward** [comment]
https://github.com/Connexions/Products.RhaptosContent/pull/5

**Comment by openstaxalina** [comment]
@openstaxalina make a copy of this issue -- the legacy part is merged; the webview part needs to go into 1/15 release.

**Comment by omehes** [comment]
Verified on 

{"date": "2019-01-11 15:20:09 CST",
 "webview": "65e33ad4775417bd5dfcb698d5cab69f1d594466 (v0.44.0)",
 "cnx-archive": "4.8.0",
 "cnx-publishing": "0.15.0",
 "oer.exports": "ymmy.yeti v0.69.0",
 "press": "8.0.1",
 "cnx-deploy": "v2.34.1"
}

FIXED
