### ISSUE TITLE
GOB content status tool: ability to delete items and rearrange queue

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#51]
## Overview
As a content manager, I want to be able to delete jobs from the queue, or rearrange jobs in the queue.

Content managers currently have this ability with the colprint, colcomplete, and collxml queue on legacy.cnx.org.

We delete items when we accidentally generated/baked them.

We re-arrange items if there is an urgent need for a PDF or rebaked book and the queue is too long to accommodate this.

## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by Bkblodget** [comment]
This will be addressed in CLI admin page
