### ISSUE TITLE
GOB: Find alternate implementation for speedup

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#52]
## Overview
We already reduced the load time for https://cnx.org/a/content-status from ~2 minutes to milliseconds; however, Ross believes this may have caused some regressions.

Therefore, Ross may need to investigate an alternate method to reduce page loading times.
## CODE
- [ ] BE find alternate implementation @rossreedstrom --- ar:4,2

## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by Bkblodget** [comment]
This will happen in future iterations of baked-pdf pipeline
