### ISSUE TITLE
GOB: Calculate and provide completion targets based on statistics of previous jobs for same content (nice to have)

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#53]
### Description
Based on previous baking processes, provide the estimated bake time and estimated time to completion.

### Technical Notes
We don't currently track the time a bake takes.

### Exit Criteria
the content status page shows the estimated bake time
the content status page shows the estimated time to completion
## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by Bkblodget** [comment]
This will happen in future iterations of baked-pdf pipeline admin page

**Comment by Bkblodget** [comment]
This will happen in future iterations of baked-pdf pipeline admin page
