### ISSUE TITLE
GOB: Improve the tab UI for monitoring content status

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#55]
### Description
As a content manager who has a lot of tabs open in my browser, I want to be able to easily find the tab for monitoring content status.
### Epic Doc
https://docs.google.com/document/d/1FynUfsptjBxSvT5o0Ioqvq3N_hSuO-q-NygL4mMCi3U/edit# (Note: this is a spin-off of story 01 in that epic)
### GitHub Bug Tracking
https://github.com/Connexions/cnx-publishing/milestone/2
## CODE
- [ ] FE Code @user --- olp ?,?,? --- ar:0,?
- [ ] BE Code @user --- olp ?,?,? --- ar:0,?
## TEST
- [ ] QA Generate test plan @user --- olp: ?,?,? --- ar:0,?
- [ ] QA Perform tests @user --- olp: ?,?,? --- ar:0,?
## Acceptance Criteria
1 Add a browser favicon
2 Display "GOB" on the tab header

**Comment by ambersdai** [comment]
- Only need for favicon remains.
- Unicorn work as the GOB tool is AW monitoring.

**Comment by Bkblodget** [comment]
This will happen in future iterations of baked-pdf pipeline admin page
