### ISSUE TITLE
Create Documentation for HTML conventions (Part 2 of 2)

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#56]
## Overview
As a Textbook Developer I want content specifications for CTE so that I can write recipes to publish books using the CTE workflow.
Gather and centralize all documentations to be able to create a content guideline for CTE## PRs
What PRs need to be merged to complete this task/feature
### Solution
Output HTML Conventions Draft at https://docs.google.com/document/d/1xxWYMgFDTaFU5lU-UVRqZWPHXLqChWpFA9r9gvpsFrs
TextbookHTML Specification Working Draft https://github.com/oerpub/TextbookHTML/blob/master/specification.asciidoc
### Epic Doc
https://docs.google.com/document/d/1FynUfsptjBxSvT5o0Ioqvq3N_hSuO-q-NygL4mMCi3U/edit#heading=h.liua0ga4vtgj
## CODE
- [ ] BE Document the types of elements that are created in baked files @philschatz --- olp: 6,10,12 --- ar: 0,11
- [ ] BE Document the attributes and elements that are needed to split up the Baked HTML file into multiple files @philschatz --- olp: 2,4,6 --- ar: 1,5
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Part 2
The types of elements that are created in baked files are documented
Attributes and elements that are needed to split up the Baked HTML file into multiple files are documented

**Comment by Bkblodget** [comment]
I'm archiving this issue because the work is being addressed in Baked-PDF
