### ISSUE TITLE
Deploy a development branch of webview

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#60]
## Overview
Size: Medium (3-5 points)
As Phil S., I want to deploy my-branch of webview to dev-like environments, so that I can get my changes tested before they are merged.

### Old Description
Right now deployments require editing a .yml .txt file generated by pip (a python commandline utility) in a private public repo and then triggering the deployment via an interface like rundeck.

Phil thinks this config file should be some place public (and support commit sha's) for dev deployments.

Michael thinks Phil didn't ask how this is done before creating this card. ;-) Michael notes that the code is in the public and commit sha's are supported.

Context: https://trello.com/c/rWRJfK7P/139-cnx-assignable-webview-10-release

## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
The existing practice of deployment using cnx-deploy can deploy a branch or specific changeset of webview.

**Comment by pumazi** [comment]
This has some relation to https://github.com/openstax/quality-assurance-meta/issues/68 & https://github.com/openstax/quality-assurance-meta/issues/72.

**Comment by helenemccarron** [comment]
This is already possible: on Rundeck, add the extra_var field:
`webview_version=v0.32.0-1-gc92b30d` (webview_version= and the version number from the previous screen)
