### ISSUE TITLE
Change canonical URL to include Book UUID and Page UUID

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#64]
## Overview
As part of "Assignable Webview" I think this was missed. the <link rel="canonical"> tag for a page only contains the Book UUID but it should contain both the Book UUID and Page UUID.
Some questions:

- should the book/page UUID's also contain the version number? (Phil thinks not so that Google does not consider different versions of the same page as duplicate/spam)

- should the <link rel="next"> and <link rel="prev"> contain the long UUID (? They currently contain the short UUID and version
## PRs
What PRs need to be merged to complete this task/feature
## Code

- FE use full uuids and versions for all three in webview @Trellouser --- olp: 4,6,10 --- ar: 0,?

## Test Plan

- [ ] QA Text prep @trellouser --- olp: ?,?,? --- ar: 0,?
- [ ] QA Text exec @trellouser --- olp: ?,?,? --- ar: 0,?

## Acceptance Criteria
Expected behavior

**Comment by ambersdai** [comment]
I think the links should contain the same thing as the canonical - the long uuid. If we leave off the book version, it's slightly possible that the current page does not exist inside the most recent version of the book. - Ross

**Comment by ambersdai** [comment]
https://openstax.slack.com/archives/C5DKG4NJE/p1495651551023113 - Amanda Shih

**Comment by ambersdai** [comment]
tech note: we should block google from legacy.cnx.org. we'll need to get approval to block google from legacy.cnx.org because it's a policy decision. - Michael Mulich

**Comment by ambersdai** [comment]
These an need to be the full uuid w/ version for all three values - Ross

**Comment by edwoodward** [comment]
This work has been completed. Closing
