### ISSUE TITLE
Idea: create a canonical URL on archive that points to the CNX.org version

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#65]
##Overview
What does this task accomplish?
## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by edwoodward** [comment]
Duplicate of https://github.com/openstax/cnx/issues/208. Closing.
