### ISSUE TITLE
De-prioritize archive in Google Search

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#67]
## Overview
Problem: archive.cnx.org continues to show up in Google search results.

Details from Ross:
We can't block archive wholesale from google (made that mistake! They can't correctly render cnx.org pages then.) Options would include:
1. block non-json urls
2. set a canonical header on the archive HTML urls, pointing to non-archive
3. provide google-bot specific redirects (that's getting into the grey zone - google doesn't like being served diff content than users).
Hmm, we definitely need to review this as part of the archive API design review
## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by Bkblodget** [comment]
This is ongoing work that will be captured by smaller tasks
