### ISSUE TITLE
Design work for discovery related to BakedPDF

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx#7]
Epic: https://docs.google.com/document/d/1Pm9X6zGH2KoZFtuZ7-fW04-MVGdzcwmFQ_a1Fs5GxQM/edit#heading=h.wuc3pn1ckk21

Kevin's Doc: https://docs.google.com/document/d/1rIW041EHBmQXVR1nvvlO7YNp2SWMN-8SOFzjVnsV0V0/edit#

**Comment by openstaxalina** [comment]
Adding release labels for tracking purposes only.

**Comment by brittweinstein** [comment]
@Bkblodget can this be closed? Is this work represented elsewhere?

**Comment by Bkblodget** [comment]
Closing - this work was broken out into two issues:

https://github.com/openstax/baked-pdf/issues/45

https://github.com/openstax/baked-pdf/issues/34
